### ISSUE TITLE
Update token URL in README

### ISSUE THREAD

**Issue by peterstory** [matlink/gplaycli#114]
The README describes a token dispenser URL which is different that the URL in the default `gplaycli.conf`. Could you clarify this discrepancy? 

## README

https://github.com/matlink/gplaycli/blob/e1262f678145a26509acd89a1be15a3f9e3f0990/README.md#changelog

> A new way for authentication has been added to GPlayCli: the tokens. I've set up a token-dispenser server (https://github.com/yeriomin/token-dispenser) at this address : https://token.matlink.fr/token/email/gplaycliacc@gmail.com . The settings has been added to credenttials.conf, and by default GPlayCli will retrieve token from this URL. If you want to keep using your credentials, set token=False in credentials.conf. You can also change the URL and setup your own token-dispenser server and then changing the token_url in the credentials.conf.

## gplaycli.conf

https://github.com/matlink/gplaycli/blob/e1262f678145a26509acd89a1be15a3f9e3f0990/gplaycli.conf#L8

**Comment by matlink** [comment]
Yes.
Token dispenser provides an URL to get a token given an email (https://token.matlink.fr/token/email/gplaycliacc@gmail.com). However, because many people uses it, the account is sometimes getting temporarily banned. So I provide multiple accounts for balancing over them, then I need that given the same URL, gplaycli gets a token of any account. That's why I changed the URL to get any token.
With the new googleplay-api, we are using GSFID which is linked to an account. So I added another route to provide either a token and a GSFID (https://matlink.fr/token/email/gsfid).
I kept the old route (https://matlink.fr/token/email) for backward compatibility and to not break running old version of gplaycli.

**Comment by peterstory** [comment]
Great, thanks for clarifying! What would you recommend for someone like me, who wants to run my own token-dispenser? I'm currently running the vanilla token-dispenser that was recommended previously, but it only returns the first part of the space-separated tuple that your https://matlink.fr/token/email/gsfid supplies. This causes gplaycli to fail with an error:

```
'gplaycli exited with \'1\'. Output: \'b\'Traceback (most recent call last):
  File "/usr/local/bin/gplaycli", line 567, in <module>
    main()
  File "/usr/local/bin/gplaycli", line 538, in main
    cli = GPlaycli(args, args.config)
  File "/usr/local/bin/gplaycli", line 117, in __init__
    self.token, self.gsfid = self.retrieve_token(self.token_url)
  File "/usr/local/bin/gplaycli", line 161, in retrieve_token
    token, gsfid = r.text.split(" ")
ValueError: need more than 1 value to unpack
\'\'.'
```

**Comment by matlink** [comment]
you're right, I should push my fork to github and make a push request to @yeriomin

**Comment by matlink** [comment]
The running version on matlink.fr is this one : https://github.com/matlink/token-dispenser

**Comment by amangupta87** [comment]
Hi, token_url = "https://matlink.fr/token/email/gsfid " is not working now as it may have expired. Can you please provide another token_url?

**Comment by matlink** [comment]
It works for me, I can get a token.
