### ISSUE TITLE
Can't download Öffi: 'Your device is not compatible with this item.'

### ISSUE THREAD

**Issue by ChristophHaag** [matlink/gplaycli#196]
```
$ gplaycli -d de.schildbach.oeffi
Error while downloading de.schildbach.oeffi : 'Your device is not compatible with this item.'
A few packages could not be downloaded :
de.schildbach.oeffi
'Your device is not compatible with this item.'
```
gplaycli 3.24
python-gpapi 0.4.3

If this message comes from the play store it's probably necessary to fake some device capabilities.

**Comment by madaratech** [comment]
Same here!

**Comment by ChristophHaag** [comment]
It's not really an issue with Öffi because it's also available in fdroid.

But com.netflix.mediaclient is also affected.

**Comment by BBerastegui** [comment]
Just FYI, you can try by iterating over other codenames:

`devices_codenames = GooglePlayAPI.getDevicesCodenames()`

That returns an array of possible codenames:

`['alien_jolla_bionic', 'angler', 'aries', 'bacon', 'bbb100', 'BRAVIA_ATV2', 'bravo', 'bullhead', 'cloudbook', 'crackling', 'cwv88s', 'eeepad', 'foster', 'fp2', 'fresh', 'fs454', 'gemini', 'gtp7510', 'gts3llte', 'hammerhead', 'hero2lte', 'honami', 'JP-1601', 'K013_1', 'kenzo', 'm201', 'm3xx', 'maguro', 'mako', 'manta', 'nxtl09', 'oneplus3', 'pico', 'sailfish', 'shamu', 'sloane', 't00q', 'Tab_8_4C', 'walleye', 'wetekplay2']`

That you can later use in gplaycli ("shamu" for example):

`gpc.device_codename = 'shamu'`

**Comment by matlink** [comment]
Are you using tokens provided by my token-dispenser instance?

**Comment by matlink** [comment]
There seems to be some trouble from my side due to race condition on providing tokens associated with a given device. From the moment where you ask for an apk and the moment you download it, any request that asks an apk but for a different device could make you face this error. I'm currently investigating.

**Comment by jr3074** [comment]
i use my own token dispenser but got the same error

**Comment by eighthave** [comment]
This made it work for me, with only sporatic fails:
```console
$ gplaycli --device-codename fp2 -d org.mozilla.firefox
```

**Comment by yurganov** [comment]
+1 on it

tried different codenames

```gplaycli --device-codename hammerhead -vvvvvvvvvvvvvvvv -p -L -d com.vividgames.realboxing2```

**Comment by eighthave** [comment]
It stopped working for me with `--device-codename fp2` and `--device-codename hammerhead`...

**Comment by ReekyMarko** [comment]
I have many applications which refuse to download with any of the codenames, even though they are supported. This includes, but is not limited to fi.caleidon.tuudo, fi.danskebank.mobilepay and com.maxmpz.audioplayer

**Comment by ametade** [comment]
I'm having the same problem. Could this be related to some Google Play changes? Does anyone managed to solve this problem?

**Comment by ardevd** [comment]
same issue here. can't download anything regardless of device type specified

**Comment by yoghi** [comment]
same issue: `gplaycli -f download -v -dc hammerhead -d de.number26.android` 
```
[INFO] GPlayCli version 3.25 [Python3.7.3]
[INFO] Configuration file is gplaycli.conf
[INFO] Device is hammerhead
[INFO] Using credentials to connect to API
[INFO] Using plaintext password
[INFO] 1 / 1 de.number26.android
[ERROR] Error while downloading de.number26.android : 'Your device is not compatible with this item.'
[ERROR] A few packages could not be downloaded :
de.number26.android
'Your device is not compatible with this item.'
```

**Comment by pabs3** [comment]
I iterated through all of the codenames in gplaycli and tried each one. I think it would be useful to get an option to automatically try all codenames until one works. 

I also wonder if gplaycli needs to add the codenames for the latest Android devices each year and try the newest phones first, since apps generally support newer phones more than older one.

You could also add a 'latest' option that would download the info for the most recently released phone from the token service.

The iteration approach eventually worked for me and angler was the only codename that worked for the app I wanted.

**Comment by pabs3** [comment]
@matlink which commits fixed this issue?

**Comment by matlink** [comment]
None. Need to try again with newer version of gplaycli and gpapi.

**Comment by pabs3** [comment]
Hmm, I don't understand, could you explain in more detail?

-- 
bye,
pabs

https://bonedaddy.net/pabs3/

**Comment by matlink** [comment]
Check comment https://github.com/matlink/gplaycli/issues/196#issuecomment-429842471. I don't know how to resolve this since it would require to have one google account per supported device. My main issue is that I'm the only one to provide token-dispenser server, so it gives more issues than it would do if other instance were freely available.

**Comment by pabs3** [comment]
I see, thanks for the info.

One option for solving this would be to create a token server queue and
have each gplaycli download user wait in that queue until it is their
turn. Downloads that started successfully would leave the queue and
downloads that take too long to start could be ejected from the queue.

-- 
bye,
pabs

https://bonedaddy.net/pabs3/

**Comment by matlink** [comment]
It would become easy to denial the service then...

**Comment by pabs3** [comment]
With a short enough timeout and rate limiting it should be possible to
mitigate that. You could also have multiple backend Google Play
accounts and one queue for each account to help mitigate any DoS.

-- 
bye,
pabs

https://bonedaddy.net/pabs3/
