### ISSUE TITLE
Cannot login to GooglePlay ( server says: NeedsBrowser )

### ISSUE THREAD

**Issue by msdos** [matlink/gplaycli#32]
Even after using the changed credentials from https://github.com/matlink/gplaycli/commit/de4bcd953c8d84717f730e0150c24efebb921c7a I'm having this error.

Don't know if it's similar to https://github.com/matlink/gplaycli/issues/30 since I'm using gplaycli credentials.

**Comment by matlink** [comment]
Is it you : https://pic.matlink.fr/7w7iGn9D/RnN72jpp ?

**Comment by msdos** [comment]
Yes.

Maybe google is changing it's security measures and now everyone will need it's own credentials when using gplaycli? If so, we need a change in documentation at least.

**Comment by matlink** [comment]
Well I don't know, I think Google blocked this login request according to some metadata from your internet connection (mostly localization) because they consider it as an unusual behaviour of this account. 
Is the bug gone? Can you try this on another machine in the same network, and with the same machine on another network (with a different public IP)?

**Comment by matlink** [comment]
I tried to use gplaycli with a 2 factors authentication enabled account and I got the same error.

**Comment by msdos** [comment]
Using these credentials https://github.com/matlink/gplaycli/commit/11ecdd78713789f81284e57dd53d54b4794a6495 it worked. I'll try with the new ones in https://github.com/matlink/gplaycli/commit/f972e5689c13da8ce15c8b249cb3966db5a6bc6e

**Comment by matlink** [comment]
Try with the new token way to use gplaycli.
