### ISSUE TITLE
Fake devices

### ISSUE THREAD

**Issue by matlink** [matlink/gplaycli#70]
Would be great to fake devices to get apps not available for the default one.
YalpStore does it well.

**Comment by portablesoft** [comment]
Is there any update on this issue? Is it possbile to migrate it from the YalpStore?

Some apps are 'Varies with device', such as https://play.google.com/store/apps/details?id=com.android.chrome

If Fake devices is supported, I think we could get all the apks of such apps.

**Comment by NoMore201** [comment]
I think there are two ways:
- expand the `device.properties` in googleplay-api with new devices, and add some code in order to be able to select one.
- be able to supply a custom `device.properties` file to googleplay-api.

There is an amazing collection of properties for a lot of common devices in the play-store-api project:
https://github.com/yeriomin/play-store-api/tree/master/src/main/resources

**Comment by matlink** [comment]
We should support both I think

**Comment by matlink** [comment]
Done with https://github.com/matlink/gplaycli/tree/3.3
